const matchData = [
  {
    "family" : "Floral Amber",
    "color" : "rgb(236,0,139)",
    "img" : "floralamber.png",
    "brand" : "JO MALONE",
    "name" : "Rose Water & Vanilla Cologne", 
  },
  {
    "family" : "Soft Amber",
    "color" : "rgb(218,12,134)",
    "img" : "softamber.webp",
    "brand" : "Santa Maria Novella",
    "name" : "Melograno Eau de Cologne", 
  },
  {
    "family" : "Amber",
    "color" : "rgb(152,0,46)",
    "img" : "amber.png",
    "brand" : "JO MALONE",
    "name" : "Vetiver & Golden Vanilla Cologne Intense", 
  },
  {
    "family" : "Woody Amber",
    "color" : "rgb(185,90,21)",
    "img" : "woodyamber.webp",
    "brand" : "Santa Maria Novella",
    "name" : "Tabacco Toscano Eau de Cologne", 
  },
  {
    "family" : "Woods",
    "color" : "rgb(187,128,59)",
    "img" : "woods.webp",
    "brand" : "CREED",
    "name" : "Royal Oud Eau de Parfum", 
  },
  {
    "family" : "Mossy Woods",
    "color" : "rgb(52,113,90)",
    "img" : "mossywoods.webp",
    "brand" : "CREED",
    "name" : "Bois du Portugal Eau de Parfum", 
  },
  {
    "family" : "Dry Woods",
    "color" : "rgb(137,132,92)",
    "img" : "drywoods.webp",
    "brand" : "CREED",
    "name" : "Aventus Eau de Parfum", 
  },
  {
    "family" : "Aromatica",
    "color" : "rgb(81,78,134)",
    "img" : "aromatica.webp",
    "brand" : "Santa Maria Novella",
    "name" : "Pot Pourri Eau de Cologne", 
  },
  {
    "family" : "Citrus",
    "color" : "rgb(255,221,0)",
    "img" : "citrus.jpg",
    "brand" : "Acqua di Parma",
    "name" : "Mirto Di Panarea Eau de Toilette", 
  },
  {
    "family" : "Water",
    "color" : "rgb(0,154,199)",
    "img" : "water.jpg",
    "brand" : "Maison Margiela",
    "name" : "Sailing Day Eau de Toilette", 
  },
  {
    "family" : "Green",
    "color" : "rgb(116,192,103)",
    "img" : "green.png",
    "brand" : "DIPTYQUE",
    "name" : "Philosykos Eau de Toilette", 
  },
  {
    "family" : "Fruity",
    "color" : "rgb(244,123,32)",
    "img" : "fruity.png",
    "brand" : "JO MALONE",
    "name" : "Blackberry & Bay Cologne", 
  },
  {
    "family" : "Floral",
    "color" : "rgb(239,65,53)",
    "img" : "floral.jpg",
    "brand" : "MARC JACOBS",
    "name" : "Perfect Eau de Toilette", 
  },
  {
    "family" : "Soft Floral",
    "color" : "rgb(241,115,172)",
    "img" : "softfloral.jpg",
    "brand" : "DIPTYQUE",
    "name" : "Eau Rose Eau de Parfum", 
  },  
]

export default matchData;